### ISSUE TITLE
ES Modules Building Failed

### ISSUE THREAD

**Issue by StimulCross** [d-fischer/tsukuru#14]
I'm trying to use `tsukuru` in my library which uses the same structure as `twurple`. The process fails on ES modules building stage. The situation is the same with `twurple` itself. After `yarn build` / `yarn rebuild` I get the following output:
```
PS C:\Dev\twurple> yarn rebuild
yarn run v1.22.19
$ tsukuru --clean
√ Cleaning CJS outputs (81ms)
√ Checking & building changed projects for CJS (91694ms)
√ Bootstrapping ESM tsconfig files (24ms)
√ Cleaning ES module outputs (20ms)
\ Building ES modules... error TS18003: No inputs were found in config file 'C:/Dev/twurple/node_modules/.cache/tsukuru/esm-bootstrap/common/tsconfig.json'. Specified 'include' paths were '["C:\\Dev\\twurple\\packages\\common\\**\\*"]' and 'exclude' paths were '["../../../../../packages/common/node_modules","../../../../../packages/common/lib","../../../../../packages/common/es"]'.
√ Building ES modules (1ms)
Done in 92.34s.
```
After building I have `lib` folders, but `es` folders are missing.

tsukuru: 0.8.0-pre.5 (0.7.4 does not build at all with complete success console output)
Node: 16.16.0
OS: Windows 10

Am I doing something wrong? 🤔

**Comment by d-fischer** [comment]
Probably a Windows issue, as I really only tested this on a Linux environment. Might be something regarding the construction of the input paths.

**Comment by StimulCross** [comment]
> Probably a Windows issue.

Yes, looks like it is. But there is a workaround. Windows currently has a feature `Windows Subsystem for Linux (WSL2)`. If I run `yarn build` from Linux shell it works as expected.

**Comment by d-fischer** [comment]
Can you try upgrading to version `0.8.0-pre.6` and check if that fixes your problems?

**Comment by StimulCross** [comment]
Now it works perfectly. Good job! 
```
PS C:\Dev\donation-alerts> yarn rebuild
yarn run v1.22.19
$ tsukuru --clean
√ Cleaning CJS outputs (32ms)
√ Checking & building changed projects for CJS (7171ms)
√ Bootstrapping ESM tsconfig files (14ms)
√ Cleaning ES module outputs (28ms)
√ Building ES modules (1375ms)
Done in 9.11s.
```
