### ISSUE TITLE
some points I encountered

### ISSUE THREAD

**Issue by zohar1000** [d-fischer/tsukuru#2]
Hi @d-fischer,

I used the library to publish a typescript package I'm writing, and it works great.
in fact, it would have saved me a couple of days if I knew about it earlier.

I understand that the library is new, and while working with it I encountered a few points
that I want to share here.
1. rimraf was missing when I tried to build my package, so I had to npm install it.
the rimraf package is listed under devDependencies section, I think it's better to place it under dependencies or peerDependencies.
2. the index.mjs file was generated with mixed slashes.
lines in the index.ts file which looks like
   **export { ZArray } from './utils/zarray';**
were generated in index.mjs file as
   **export { ZArray } from "./utils\\\\zarray.mjs";**
I didn't dig into your source code but I guess it's because the path construction was made on a windows machine caused it. This can cause problems on linux systems, so I wrote a script to fix
and now it's running as a stage after the build.
If you want I can contribute to fix this.
3. The readme file shows how to set the package.json file, however I wasn't sure about the 
settings in the tsconfig.json file. I played with the definitions there and now it's seems to work, but
I'm not sure for certain that all settings are correct.
I attached below my tsconfig.json file, can you kindly verify the settings are correct?

Other then that I want to thank you about this library, the idea behind it is just fine and it's 
better then the rest of the solutions I found so far.

> {
  "compilerOptions": {
    "target": "es2015",
    "module": "CommonJS",
    "declaration": true,
    "outDir": "./lib",
    "strict": true,
    "noImplicitAny": false
  },
  "lib": [
    "es2015",
    "dom",
    "es5"
  ],
  "include": ["src"],
  "exclude": ["node_modules", "**/__tests__/*"]
}

**Comment by d-fischer** [comment]
First, thanks for using this little tool! I really just made it for myself and haven't even been able to push my first package using it (soon™️ 😄), so you're really early!

Please extract the first two bullet points into their own issues so I can link them with their corresponding fixes properly when I do fix them.

As for your configuration, there's hardly anything that *can* be wrong. For the CommonJS build, I currently just take it as is, so it needs to have `"module": "commonjs"` and an `outDir` that corresponds to the `main` entry in the package.json file. The ESM build overwrites these values anyway, so nothing to worry about on that part.

I might consider exiting when the `module` setting is not `commonjs`, or just using `commonjs` and warning if the config file has a `module` setting. Inferring the directories from the package.json file is also a possibility.
