### ISSUE TITLE
rimraf is missing when building the package

### ISSUE THREAD

**Issue by zohar1000** [d-fischer/tsukuru#3]
hi @d-fischer,

rimraf was missing when I tried to build my package, so I had to npm install it.
the rimraf package is listed under devDependencies section, I think it's better to place it under dependencies or peerDependencies.

**Comment by zohar1000** [comment]
I see now that you already addressed it, so this issue can be closed.

**Comment by d-fischer** [comment]
Correct, this was fixed in 155e88b and released as v0.2.3 already.
