### ISSUE TITLE
index.mjs file was generated with mixed slashes

### ISSUE THREAD

**Issue by zohar1000** [d-fischer/tsukuru#4]
hi @d-fischer,

the index.mjs file was generated with mixed slashes.
lines in the index.ts file which looks like
export { ZArray } from './utils/zarray';
were generated in index.mjs file as
export { ZArray } from "./utils\\zarray.mjs";
I didn't dig into your source code but I guess it's because the path construction was made on a windows machine caused it. This can cause problems on linux systems, so I wrote a script to fix
and now it's running as a stage after the build.
If you want I can contribute to fix this.

**Comment by zohar1000** [comment]
I see now that you already addressed it, so this issue can be closed.

**Comment by d-fischer** [comment]
Correct, this was fixed in 182b59a and released as v0.2.3 already.
